server:
  port: 8998

logging:
  path: logs
  file: userManager.log

spring:
  application:
    name: userManager
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/course?serverTimezone=GMT&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456

mybatis:
  type-aliases-package: com.course.model
  mapper-locations:
    - mapper/*